functional:
  - Сайт дает возможность просматривать игры игроков в записи после завершения игры обоими игроками
  - Сайт дает возможность создать и подключиться к уже созданной игре
  - Сайт начисляет очки за победу в игре и снимает очки за поражение 
  - На основе начисленных и снятых очков ведется рейтинг игроков, который можно просмотреть
  - На сайте работает чат, в котором зарегистрированные пользователи могут общаться
  - На сайте во время игры можно сменить язык отображения задач
  - На сайте есть возможность следить за играющим игроком
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Проверить сайт на устойчивомть от различного вида инъекций
  - Проверить скорость загрузки сайта при различных переходах и действиях
  - Проверить адаптивность верстки сайта
  
