functional:
  - Сайт должен давать возможность просматривать игры игроков 
  - Сайт должен давать возможность играть со случайным человеком, ботом, или приглашенным другом
  - На сайте есть возможность просмотра рейтинга по очкам, полученным за игры 
  - На сайте должен работать чат, в котором зарегистрированные пользователи могут общаться, приглашать в игру и просматривать игры 
  - На сайте во время игры можно сменить язык отображения задач
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Проверить сайт на устойчивомть от различного вида инъекций
  - Проверить скорость загрузки сайта при различных переходах и действиях
  - Проверить адаптивность верстки сайта
